import { michroma } from "./Font/font";
import "./globals.css";
import Navbar from "./UI/navbar";

export const metadata = {
  title: "OlahragaYuk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${michroma.className} antialiased `}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
